### ISSUE TITLE
create fake hotel

### ISSUE THREAD

**Issue by eliezerwohl** [eliezerwohl/homework1124#1]

**Comment by eliezerwohl** [comment]
create 15-30 fake hotels, assign a star rating, amenities, and price.  doesn't need to be put into code just yet

**Comment by Victor-Villacis** [comment]
@eliezerwohl lets stick to 10. Not being able to use more than 1html page, I think 30 coded hotels will start to get messy pretty quick

**Comment by eliezerwohl** [comment]
went with 15 hotels.  5 for each state
