### ISSUE TITLE
Put search bar above results, create two panels for each

### ISSUE THREAD

**Issue by eliezerwohl** [eliezerwohl/homework1124#13]

**Comment by Victor-Villacis** [comment]
I don't know what you mean with this?

**Comment by eliezerwohl** [comment]
ahh.  Wasn't clear.  Just meant I think it would look better if search results where in a panel to style it.  Now it's just kinda of floating in nothing.  Also, you put the search bar in the nav bar, so that what what I mean by put the search bar above results
